### ISSUE TITLE
Cannot compile RoomScheduler.java

### ISSUE THREAD

**Issue by gentig** [NEHAERSAVADLA/MSCS721LRoomScheduler#1]
Tried both IDE and CLI to compile it and did not work

**Comment by praneethm** [comment]
Tested, i am able to compile and run without any issues.

The entire folder should be placed in src folder if trying to run through IDE
e.g. src/com/....
Secondly if being compiled through CLI dependency jar files have to be provided.
<img width="686" alt="screen shot 2018-02-15 at 3 44 54 pm" src="https://user-images.githubusercontent.com/25289019/36280210-8d026cfa-1267-11e8-911c-16a36c0f000f.png">
